parameters:
    piappgedmo.manager.formbuilder.model.breadcrumb.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetBreadcrumb
    piappgedmo.manager.formbuilder.model.block.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetBlock
    piappgedmo.manager.formbuilder.model.content.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetContent
    piappgedmo.manager.formbuilder.model.contact.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetContact
    piappgedmo.manager.formbuilder.model.slide.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetSlide
    piappgedmo.manager.formbuilder.model.menu.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetMenu
    piappgedmo.manager.formbuilder.model.organigram.class: PiApp\GedmoBundle\Manager\FormBuilder\PiModelWidgetOrganigram

services:
    #
    # configuration of the FORM BUILDER classes
    #

    pi_app_gedmo.formbuilder_manager.model.breadcrumb:
        class: %piappgedmo.manager.formbuilder.model.breadcrumb.class%
        arguments: ['@service_container']

    pi_app_gedmo.formbuilder_manager.model.block:
        class: %piappgedmo.manager.formbuilder.model.block.class%
        arguments: ['@service_container']

    pi_app_gedmo.formbuilder_manager.model.content:
        class: %piappgedmo.manager.formbuilder.model.content.class%
        arguments: ['@service_container']

    pi_app_gedmo.formbuilder_manager.model.contact:
        class: %piappgedmo.manager.formbuilder.model.contact.class%
        arguments: ['@service_container']

    pi_app_gedmo.formbuilder_manager.model.slide:
        class: %piappgedmo.manager.formbuilder.model.slide.class%
        arguments: ['@service_container']

    pi_app_gedmo.formbuilder_manager.model.menu:
        class: %piappgedmo.manager.formbuilder.model.menu.class%
        arguments: ['@service_container']

    pi_app_gedmo.formbuilder_manager.model.organigram:
        class: %piappgedmo.manager.formbuilder.model.organigram.class%
        arguments: ['@service_container']
